baseURL = 'https://dominikhofer.me/'
locale = 'en-US'
title = 'Dominik Hofer'
timeZone = 'Europe/Zurich'
theme = 'dominik'

[markup.highlight]
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]

[minify.tdewolff.html]
keepQuotes = true

[permalinks]
posts = '/:slug/'
races = '/:slug/'

[outputFormats.PostsRSS]
mediaType = 'application/rss+xml'
baseName = 'rss'
isPlainText = true
notAlternative = false

[outputs]
home = ['HTML', 'PostsRSS']
section = ['HTML']
taxonomy = ['HTML']
term = ['HTML']

[caches.getresource]
maxAge = 0

[params]
version = '3.0'
location = 'Bern, CH'
description = 'Dominik Hofer. Striving for Simplicity in a complex World.'
replyEmail = 'hi@dominikhofer.me'

[params.atproto]
did = 'did:plc:fthx2gjakdj4ynxxu5vysjty'

[params.bookhive]
profile = 'https://bookhive.buzz/profile/dominik.social'

[params.semble]
profile = 'https://semble.so/profile/dominik.social'
findsCollection = 'at://did:plc:fthx2gjakdj4ynxxu5vysjty/network.cosmik.collection/3mmg5d62hv62f'
